//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sys_jwxt.rc
//
#define IDC_BTN_ADDJWQUERY              1
#define IDC_BTN_SYS_ADDTCH              1
#define IDC_BTN_SYS_UPDATETCH           2
#define IDC_BTN_SYS_DELTCH              3
#define IDC_BTN_SYS_ADDJW               4
#define IDC_BTN_SYS_UPDATEJW            5
#define IDC_BTN_SYS_DELJW               6
#define IDC_BTN_JW_IMPTSTU              7
#define IDC_BTN_JW_IMPTTCH              8
#define IDC_BTN_SYS_ADDSTU              9
#define IDC_BTN_SYS_UPDATESTU           10
#define IDC_BTN_SYS_DELSTU              11
#define IDC_BTN_JW_ADDCOURSE            12
#define IDC_BTN_JW_DELCOURSE            13
#define IDD_SYS_JWXT_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_LOGINED_SYSTEM              129
#define IDD_LOGINED_TEACHER             130
#define IDD_LOGINED_STUDENT             131
#define IDD_LOGINED_JW                  132
#define IDD_SYSTEM_ADDTCH               137
#define IDD_SYSTEM_DELTCH               139
#define IDD_SYSTEM_UPDATETCH            141
#define IDD_SYS_JWXT_WELCOME            144
#define IDB_WELCOME                     146
#define IDI_MAIN                        147
#define IDD_SYSTEM_ADDJW                148
#define IDD_SYSTEM_UPDATEJW             149
#define IDD_SYSTEM_DELJW                150
#define IDD_JW_PUBLISH                  158
#define IDD_SYSTEM_ADDSTU               160
#define IDD_SYSTEM_DELSTU               161
#define IDD_SYSTEM_UPDATESTU            162
#define IDD_JW_ADDCOURSE                166
#define IDD_JW_DELCOURSE                167
#define IDD_CHANGEPWD                   168
#define IDD_TCH_INPUTSCORE              169
#define IDD_POP_INPUTSCORE              171
#define IDC_EDIT_LOGINID                1000
#define IDC_EDIT_LOGINPWD               1001
#define IDR_USER_SYSTEM                 1002
#define IDR_USER_JW                     1003
#define IDR_USER_TEACHER                1004
#define IDR_USER_STUDENT                1005
#define IDC_BTN_LOGIN                   1006
#define IDC_BTN_EXIT                    1007
#define IDC_BTN_SYS_EXIT                1007
#define IDC_LOGINEDMESSAGE              1008
#define IDC_BTN_SYS_JW                  1011
#define IDC_SYS_ADODC                   1012
#define IDC_DATAGRID_JWADMIN            1013
#define IDC_DATAGRID_MESG               1018
#define IDC_BTN_SYS_TCH                 1019
#define IDC_BTN_SYS_PUB                 1020
#define IDC_EDIT_ID                     1021
#define IDC_BTN_SYS_STU                 1021
#define IDC_EDIT_PWD                    1022
#define IDC_BTN_SYS_DELPUBLOG           1022
#define IDC_COMBO_SEX                   1023
#define IDC_EDIT_NAME                   1024
#define IDC_COMBO_DELITEM               1024
#define IDC_EDIT_AGE                    1025
#define IDC_EDIT_DELMSG                 1025
#define IDC_BROKEN                      1026
#define IDC_BTN_CHANGE                  1027
#define IDC_COMBO_CHANGEITEM            1028
#define IDC_EDIT_CHANGEMSG              1029
#define IDC_STATIC_BROKEN               1037
#define IDC_EDIT_CHANGE                 1040
#define IDC_BTN_JW_EXIT                 1042
#define IDC_BTN_SKIN                    1045
#define IDC_BTN_JW_IMPT_STUDENT         1046
#define IDC_BTN_JW_IMPT_TEACHER         1047
#define IDC_BTN_JW_UPDATESTU            1048
#define IDC_BTN_JW_UPDATETCH            1049
#define IDC_BTN_JW_SETCOURSE            1050
#define IDC_BTN_JW_PUB                  1051
#define IDC_BTN_JW_SWITCH               1052
#define IDC_LIST_IMPT                   1053
#define IDC_JW_SHOWPUBTIME              1055
#define IDC_RICHEDIT_PUB                1057
#define IDC_JW_SHOWPUB                  1058
#define IDC_SYS_SHOWPUB                 1059
#define IDC_SYS_SHOWPUBTIME             1060
#define IDC_HEADER                      1074
#define IDC_EDIT_TID                    1076
#define IDC_EDIT_CREDIT                 1077
#define IDC_BTN_TCH_EXIT                1077
#define IDC_BTN_TCH_PERSON              1078
#define IDC_BTN_TCH_CHANGEPWD           1079
#define IDC_BTN_TCH_INPUTSCORE          1080
#define IDC_TCH_SHOWPUB                 1081
#define IDC_TCH_SHOWPUBTIME             1082
#define IDC_TCH_PERSON                  1083
#define IDC_TCH_ID                      1084
#define IDC_TCH_NAME                    1085
#define IDC_TCH_SEX                     1086
#define IDC_TCH_AGE                     1087
#define IDC_TCH_SHOWID                  1088
#define IDC_TCH_SHOWNAME                1089
#define IDC_EDIT_ORGINPWD               1089
#define IDC_TCH_SHOWSEX                 1090
#define IDC_EDIT_NEWPWD                 1090
#define IDC_TCH_SHOWAGE                 1091
#define IDC_EDIT_REPEATPWD              1091
#define IDC_TCH_LIST_COURSE             1092
#define IDC_TCH_HEADER                  1093
#define IDC_ADODC_SC                    1094
#define IDC_DATAGRID_INPUTSCORE         1095
#define IDC_EDIT_SOCRE                  1096
#define IDC_BTN_STU_EXIT                1097
#define IDC_STU_SHOWPUB                 1098
#define IDC_STU_SHOWPUBTIME             1099
#define IDC_BTN_STU_PERSON              1100
#define IDC_BTN_STU_CHANGEPWD           1101
#define IDC_BTN_STU_SC                  1102
#define IDC_BTN_STU_GETSCORE            1103
#define IDC_STU_PERSON                  1105
#define IDC_STU_ID                      1106
#define IDC_STU_SHOWID                  1107
#define IDC_STU_NAME                    1108
#define IDC_STU_SHOWNAME                1109
#define IDC_STU_SEX                     1110
#define IDC_STU_SHOWSEX                 1111
#define IDC_STU_AGE                     1112
#define IDC_STU_SHOWAGE                 1113
#define IDC_STU_HEADER_ONE              1114
#define IDC_STU_HEADER_TWO              1115
#define IDC_LIST_PRESELECT              1116
#define IDC_LIST_SELECTED               1117
#define IDC_BTN_ADDCOURSE               1118
#define IDC_BTN_DELCOURSE               1119
#define IDC_LIST_SCORE                  1120
#define IDC_STU_HEADER                  1121

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
